import{i as a,a as v,S}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();function C(){a.error({icon:"",backgroundColor:"#ef4040",position:"topRight",message:"You forgot to type something",messageColor:"white"})}let u="";async function h(e,t=1){u=e;const s="https://pixabay.com/api/",n=new URLSearchParams({key:"44031120-3f1a866ec56678536c033b40b",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15});try{const{data:o}=await v(`${s}?${n}`);return o.totalHits===0?(a.error({icon:"",backgroundColor:"#ef4040",position:"topRight",message:"Sorry, there are no images matching your search query. Please, try again!",messageColor:"white"}),[]):o.hits}catch(o){return console.error(o.message),a.error({icon:"",backgroundColor:"#ef4040",position:"topRight",message:"An error occurred while fetching images. Please try again later.",messageColor:"white"}),[]}}const m=15;let i;const f=document.querySelector(".gallery"),l=document.querySelector(".js-load-more"),g=document.querySelector(".loader");let d=1;function $(e){f.innerHTML=e.map(t=>b(t)).join(""),i&&i.destroy(),i=new S(".gallery a",{captionDelay:250,captionsData:"alt"}),e.length<m?(l.style.display="none",y()):l.style.display="block"}function q(e){f.insertAdjacentHTML("beforeend",e.map(t=>b(t)).join("")),i.refresh()}l.addEventListener("click",P);async function P(){if(u){d+=1,w();try{const e=await h(u,d);e.length>0&&(q(e),window.scrollBy({left:0,top:document.body.scrollHeight,behavior:"smooth"})),e.length<m&&(a.error({icon:"",backgroundColor:"blue",position:"topRight",message:"We're sorry, but you've reached the end of search results.",messageColor:"white"}),l.style.display="none")}catch(e){console.error(e.message)}finally{y()}}}function b(e){return`
    <div class="photo-card">
      <a class="link" href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
        <div class="info">
        <li><h3 class="info-title">Likes</h3><p class="info-text">${e.likes}</p></li>
        <li><h3 class="info-title">Views</h3><p class="info-text">${e.views}</p></li>
        <li><h3 class="info-title">Comments</h3><p class="info-text">${e.comments}</p></li>
        <li><h3 class="info-title">Downloads</h3><p class="info-text">${e.downloads}</p></li>
      </div>
      </a>
    </div>
  `}function w(){g.style.display="block"}function y(){g.style.display="none"}function x(){d=1,f.innerHTML=""}const R=document.querySelector(".form"),p=document.querySelector(".input"),L=document.querySelector(".js-load-more");L.style.display="none";R.addEventListener("submit",async e=>{e.preventDefault(),x();const t=p.value.trim();if(t.length===0){C(),L.style.display="none";return}w(),p.value="";try{const s=await h(t);$(s)}catch(s){console.log(s.message)}finally{y()}});
//# sourceMappingURL=commonHelpers.js.map
