import{i as a,a as S,S as C}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();function $(){a.error({icon:"",backgroundColor:"#ef4040",position:"topRight",message:"You forgot to type something",messageColor:"white"})}let u="";async function m(e,t=1){u=e;const s="https://pixabay.com/api/",i=new URLSearchParams({key:"44031120-3f1a866ec56678536c033b40b",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15});try{const{data:o}=await S(`${s}?${i}`);return o.totalHits===0?(a.error({icon:"",backgroundColor:"#ef4040",position:"topRight",message:"Sorry, there are no images matching your search query. Please, try again!",messageColor:"white"}),[]):o.hits}catch(o){return console.error(o.message),a.error({icon:"",backgroundColor:"#ef4040",position:"topRight",message:"An error occurred while fetching images. Please try again later.",messageColor:"white"}),[]}}const g=15;let n;const f=document.querySelector(".gallery"),l=document.querySelector(".js-load-more"),b=document.querySelector(".loader");function q(e){f.innerHTML=e.map(t=>w(t)).join(""),n?n.refresh():n=new C(".gallery a",{captionDelay:250,captionsData:"alt"}),e.length<g?(l.style.display="none",p()):l.style.display="block"}function y(e){f.insertAdjacentHTML("beforeend",e.map(t=>w(t)).join("")),n&&n.refresh()}l.addEventListener("click",P);let d=1;async function P(){if(u){d+=1,L();try{const e=await m(u,d);e.length>0&&y(e),e.length<g&&(a.error({icon:"",backgroundColor:"blue",position:"topRight",message:"We're sorry, but you've reached the end of search results.",messageColor:"white"}),l.style.display="none"),y(e),window.scrollBy({left:0,top:document.body.scrollHeight,behavior:"smooth"})}catch(e){console.error(e.message)}finally{p()}}}function w(e){return`
    <div class="photo-card">
      <a class="link" href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
        <div class="info">
        <li><h3 class="info-title">Likes</h3><p class="info-text">${e.likes}</p></li>
        <li><h3 class="info-title">Views</h3><p class="info-text">${e.views}</p></li>
        <li><h3 class="info-title">Comments</h3><p class="info-text">${e.comments}</p></li>
        <li><h3 class="info-title">Downloads</h3><p class="info-text">${e.downloads}</p></li>
      </div>
      </a>
    </div>
  `}function L(){b.style.display="block"}function p(){b.style.display="none"}function x(){d=1,f.innerHTML=""}const R=document.querySelector(".form"),h=document.querySelector(".input"),v=document.querySelector(".js-load-more");v.style.display="none";R.addEventListener("submit",async e=>{e.preventDefault(),x();const t=h.value.trim();if(t.length===0){$(),v.style.display="none";return}L(),h.value="";try{const s=await m(t);q(s)}catch(s){console.log(s.message)}finally{p()}});
//# sourceMappingURL=commonHelpers.js.map
